### ISSUE TITLE
Add GEM XSum to Full Benchmark

### ISSUE THREAD

**Issue by epavlick** [bigscience-workshop/evaluation#12]
including COVID+bfp02 challenge sets

**Comment by aobaruwa** [comment]
I'd be happy to contribute to eval'ing on XSum.

**Comment by Shashi456** [comment]
The templates for this already exist but nothing specific for the challenge sets mentioned, they can be found [here](https://github.com/bigscience-workshop/promptsource/blob/main/promptsource/templates/xsum/templates.yaml). Can mark this as closed

**Comment by jzf2101** [comment]
See bigscience-workshop/promptsource#745

**Comment by jzf2101** [comment]
@awebson does this mean we should close without the PR?

**Comment by awebson** [comment]
Yeah #745 seems good. Ask me again about what's the deal with the challenge set during our next meeting. Closing this now. Thanks!
