### ISSUE TITLE
Adding WMT to simple_benchmark

### ISSUE THREAD

**Issue by wilsonyhlee** [bigscience-workshop/evaluation#2]
Per [request](https://github.com/bigscience-workshop/Megatron-DeepSpeed/issues/22) by the modeling WG, we'd like to create a simple evaluation benchmark. 

This issue tackles adding the [WMT](https://huggingface.co/datasets/wmt19) dataset to the benchmark.

**Comment by arunraja-hub** [comment]
I would like to contribute to this!
