### ISSUE TITLE
Add XSum to Full Benchmark

### ISSUE THREAD

**Issue by aobaruwa** [bigscience-workshop/evaluation#41]

**Comment by wilsonyhlee** [comment]
I think the goal is to only add datasets that are on this [list](https://docs.google.com/presentation/d/1mvCcdYzA5jZgsDzwwGpOXrZvN4ygi-_M0Ubtuj-R_r0/edit#slide=id.ge53c1dbdd7_0_30), and it doesn't look like XSum is on it. Can you confirm, @epavlick?

**Comment by aobaruwa** [comment]
Right, CRD3 is the selected dataset for text summarization. So, I'm closing the issue

**Comment by epavlick** [comment]
Actually this is part of GEM--we expanded out GEM and created one issue per GEM task that we want to include (since we weren't including all tasks). Reopening.

**Comment by wilsonyhlee** [comment]
I think [this other issue](https://github.com/bigscience-workshop/evaluation/issues/12) was meant for XSum as a part of GEM?
